"""added likes column

Revision ID: 45f9f9998726
Revises: 07860ef2c7a5
Create Date: 2023-03-14 12:47:27.492841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f9f9998726'
down_revision = '07860ef2c7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
